[project]
name = "cu-chat"
version = "0.1.0"
description = "AI Chatbot for Chandigarh University"
dependencies = [
    "Flask==2.3.2",
    "google-generativeai==0.7.2",
    "sentence-transformers==2.2.2",
    "huggingface_hub==0.16.4",
    "faiss-cpu==1.7.4",
    "PyMuPDF==1.22.5",
    "pymongo==4.6.2",
    "numpy==1.24.3",
    "nltk==3.8.1",
    "pytesseract==0.3.10",
    "pillow==10.0.0",
    "pinecone-client==2.2.2",
    "gunicorn==20.1.0",
    "torch==2.6.0+cpu",
    "torchvision==0.21.0+cpu",
    "dotenv",
]

[project.scripts]
start = "gunicorn:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --log-level debug app:app"